spring.application.name=transportadora


spring.datasource.url=jdbc:postgresql://localhost:5433/transportadora
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl-auto: update (cria/atualiza tabelas), create, create-drop, validate, none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
